### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dirkseidensticker** [ISAAKiel/mortAAR#1]
install_github('ISAAKiel/mortAAR') throws the following error:

```
Downloading GitHub repo ISAAKiel/mortAAR@master
from URL https://api.github.com/repos/ISAAKiel/mortAAR/zipball/master
Installing mortAAR
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpF2gZuF/devtoolsd083f8a55e8/ISAAKiel-mortAAR-43265aa' --library='/home/dirk/R/x86_64-pc-linux-gnu-library/3.3'  \
  --install-tests 

* installing *source* package ‘mortAAR’ ...
** R
Error in parse(outFile) : 
  /tmp/RtmpF2gZuF/devtoolsd083f8a55e8/ISAAKiel-mortAAR-43265aa/R/input_functions.R:63:2: Unerwartete(s) 'else'
62: }
63: }else
     ^
ERROR: unable to collate and parse R files for package ‘mortAAR’
* removing ‘/home/dirk/R/x86_64-pc-linux-gnu-library/3.3/mortAAR’
Fehler: Command failed (1)
```

I think the line in question should be like:
```
  }
  if(length(methode)==1){
      meth=rep(methode,ceiling(max(asd$ende)/methode))
  }
```

As local `setwd()` is set within `input_functions.R` and `Siedlungsbestattungen_ueberblick.txt` is missing from the repo, I'm unable to `install_local()` and test the patch.

**Comment by MartinHinz** [comment]
Actually, I think there is a closing bracket missing. The else branch seems to belong to the `if(is.character(methode))` and seems to handle that case that a non-character method parameter is specified. The whole thing might look like this:

```
  if(is.character(methode)){
    if(methode=="Standard"){
      meth=c(1,4)
      while(sum(meth)<max(asd$ende)){
        meth=c(meth,5)
      }
    }else if(methode=="Equal5"){
      meth=rep(5,ceiling(max(asd$ende)/5))
    }else{
      meth=c(1,4)
      while(sum(meth)<max(asd$ende)){
        meth=c(meth,5)
      }
    }
  }
  else{
    if(length(methode)==1){
      meth=rep(methode,ceiling(max(asd$ende)/methode))
    }else{
      meth=methode
    }
  }
```
Additionally, when correcting this, R complains about:
```
Fehler in setwd("C:\\Users\\Wolfgang\\Documents\\ISAAKiel\\Mortar") (von input_functions.R#9) : 
  kann Arbeitsverzeichnis nicht wechseln
```

Would be good to remove such leftovers from testing like setting working directory and input of test data sets before pushing... :-)

**Comment by MartinHinz** [comment]
Thanks, Dirk, by the way!

**Comment by dirkseidensticker** [comment]
@MartinHinz Thanks and your are right, it looks more like the missing closing bracket is causing the problem. That was my first impression as well, but after adding one I still got an error message concerning the surplus else-statement. That's why I thought it was the statement itself. But due to the `setwd()`-leftover I wasn't able to test thoroughly. Best

**Comment by nevrome** [comment]
As far as I understand the problem, input_functions.R is not prepared to be built or checked within the package. Therefore it has to be excluded from the build process - otherwise the other teams won't be able to continue testing. 

The first solution that came to my mind, was to add the file temporarly to `.Rbuildignore`:
`devtools::use_build_ignore("input_functions.R")`

Unfortunately that doesn't work well with RStudio. See: 
- https://support.rstudio.com/hc/en-us/community/posts/200654836-Build-and-Reload-Package-does-not-respect-Rbuildignore
- http://stackoverflow.com/questions/25559606/the-correct-use-of-devtools-and-or-rstudio-with-respect-to-rbuildignore
- http://stackoverflow.com/questions/13182634/rbuildignore-and-excluding-directories

**Comment by FFaupel** [comment]
Hi Guys!
Sorry for that! I solved the problem, it should work now. Anyway, the Input part is not ready jet....
Best

**Comment by nevrome** [comment]
@FFaupel Seems to work. Thanks.
