### ISSUE TITLE
PreRelease ToDo: Vignette

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/mortAAR#10]
The vignette should tell a story and present the strengths and possibilities of the package.

Nils suggested a comparisons of different Iron Age settlements. 

@ archaeologists: the non-archaeologists could participate after you give us some content/contextual information. 

helpful link: http://r-pkgs.had.co.nz/vignettes.html

**Comment by nmueller18** [comment]
I have finished the text work on the extended vignette. I still have to add some references, but otherwise I would consider it complete.
@ctietze91  I would be very grateful if you could have a look at the English.
@dakni: As non-archaeologist ...

**Comment by dakni** [comment]
@nmueller18 very nice! I enjoyed reading it and think, that I as non-archaeologist understand the necessity of the points raised as well as the usefulness of the package; i changed just the wrong term "development country" and put LaTeX formatting around the Keyfitz equations (for the sake of readability;)

language revise is still necessary. Since @ctietze91 wanted to do this I did not change anything related to this.

**Comment by nmueller18** [comment]
Thank you for your kind feedback!  :-)

**Comment by ctietze91** [comment]
Okay. I'm done. Just forgot to push it yesterday. There are still a few questions though:

l. 16:
-"many-digit numbers" is somehow not a wording which I could find as a special expression
->soll das 'vielzahlig' ausdrücken? something different?
-the argumentation begins with a "on the one hand", but there is no "on the other hand", I'll  exchange this one with a different introduction wording. Also you normally use this phrase when you have 2 arguments and here at least 3 are listed.

l. 37:
-the sentence: The verdict of N. Keyfitz (@keyfitz_applied_1977, 13) -- „The uniform distribution of deaths […] leads to nax = n/2, but this is not acceptable when the age interval n is as wide as 5 years.“ -- has certainly its validity when dealing with modern census data, but might be disregarded for older individuals, as the empirical value for age classes > 5 years is very close to 2.5, the computed value (empirically, it mostly hovers between 2.45 and 2.65 as older individuals tend to die later than within the middle of their class. This is far more difficult to generalize than for the younger age classes [see below]). 
->the sentence before the brackets ends into nothing, either there should be more behind the brackets or it should be deleted or worked into the sentence before that

l. 58:
-What do you want to say with this sentence: Unfortunately, the authors do not report how well the new results corresponded to those done formerly.   ?

l. 207:
-here the first part of the sentence also ends in the middle: While every individual counted as "1", with the Magdalenenberg data each age range comprises a different number of individuals.

Besides: Could @nmueller18  or somebody else look at my "[xxx]" included in the text? These are suggestions on how the sentence could be changed. I would appreciate some feedback on them.

**Comment by nmueller18** [comment]
I.16: "vielstellig" would be more to the point. Agreed concerning "on the one hand".
l.37: please read it again. "the computed vale" is related to "2.5". To make it easier to comprehend, a solution could be "the computed value (5 divided by 2)"
l.58: The authors do not compare their results with those of an older investigation of the same individuals.
l.207: Münsingen data: each line was one individual, Magdalenenberg data: each line (= age range) concerns more than one individual. While the sentence might not be good English, it is complete.

I will look at the square brackets! Thank you for your thorough work!

**Comment by ctietze91** [comment]
Okay, perfect.
I worked in the changes you referred to. Besides whats in the square brackets, that was the last thing.

**Comment by nmueller18** [comment]
I was ill for some days so I will not be able to finish the extended Vignette before our departure. I hope to complete it in Slovakia.

**Comment by nmueller18** [comment]
Completed extended vignette!
