### ISSUE TITLE
PreRelease ToDo: Readme.md

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/mortAAR#13]
make people curious [or at least help them to understand what `mortAAR` is about]..., i.e. describe the package, its ease of use, provided exemplary figures, ...

**Comment by MartinHinz** [comment]
References to manual and vignettes are not working on the github page. Link is currently https://github.com/ISAAKiel/mortAAR/blob/master, should be https://github.com/ISAAKiel/mortAAR/tree/master/vignettes for the vignettes and https://github.com/ISAAKiel/mortAAR/tree/master/man for the manual?

**Comment by MartinHinz** [comment]
Damn, to big fingers... Sorry.

**Comment by nevrome** [comment]
I suggest to remove the links altogether until release. Afterwards we can either link to https://isaakiel.github.io/ or to CRAN. The vignettes and the manual will be available there in a nice and prerendered format.

**Comment by nmueller18** [comment]
What is missing in the Read.me right now? Perhaps we can close the issue?

**Comment by nevrome** [comment]
yep
