### ISSUE TITLE
PreRelease Diskussion: output of life.table

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/mortAAR#19]
`life.table` currently takes either a single data.frame or a list of data.frames as input. Each of these data.frames needs the columns **a** and **Dx**. `life.table` then calculates stuff and returns a mortaar_life_table_list of mortaar_life_tables (more or less a list of data.frames) with all the input variables and the newly calculated variables. 

This method is a bit inconvenient and error-prone. Inconvenient first of all because the users always get's a mortaar_life_table_list, even if he just wants to calculate one life table. I suggest to change the output of `life.table` to a  mortaar_life_table in case of only one input data.frame. 

Error-prone because a mortaar_life_table has a potentially inconsistent set of variables. Imagine for example that the input data.frame looks something like this: 

     test <- data.frame(a = rep(5, 12), Dx = abs(round(rnorm(12)*50, 0)), fluff = 1:12, dx = 12:1)
     life.table(test)

Here there are not only **a** and **Dx**, but also the completely unrelated variables **fluff** and **dx**. The resulting mortaar_life_table will contain all the usual life table variables and also the variable **fluff**. The initial **dx** on the other hand gets overwritten, because it happens to have the same name as a variable that's calculated in `life.table`.

I see some possible solutions for this inconsistency. Either we keep all the additional input variables and give our new variables more rare names (maybe by adding a "." in front of the names -> ".dx"/".ex"/... - this solution is applied for example by `broom::augment`) or we scrape away the additional input variables beyond **a** and **Dx**. 

The first approach allows more convenient workflows: The user can keep everything in one table. The second approach may be a bit more stable, because a mortaar_life_table always looks exactly the same. 

Another idea: We keep all the additional input variables and warn the user in case of a name collision. I like this idea.

**Comment by nmueller18** [comment]
I would vote for a warning, but then for throwing away any possible additional variables with overwriting. I cannot think of any use keeping them would have.
