### ISSUE TITLE
Proposal for release names

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/mortAAR#21]
For the release names, how about learning from the successful (SpaceX) and naming the releases after the ships from the Culture novels?

https://en.wikipedia.org/wiki/List_of_spacecraft_in_the_Culture_series

Some examples:

Of Course I Still Love You	
Kiss My Ass	
Irregular Apocalypse	
The Hand of God 137	
Ultimate Ship The Second
The Precise Nature Of The Catastrophe
Just Read the Instructions

**Comment by nevrome** [comment]
Nice! I suggest to use the [Dumb Ways to Die](https://www.youtube.com/watch?v=IJNR2EpS0jw) character list. It's maybe more appropriate than spaceships ;-) 

http://dumbway2sdie.wikia.com/wiki/Characters

Numpty
Hapless
Pillock
Dippy
Dummkopf
...

**Comment by MartinHinz** [comment]
Nothing wrong with spaceships!

But alternatively (Clemens and I discussed about possible copyright issues), the first names of directors of zombie movies:

Burr (Stolz und Vorurteil und Zombies)
Yeon (Seoul Station)
Shinsuke (I am a Hero)
Kyle (Night of the Living Deb)
Stanton (Navy Seals vs. Zombies)
Dominik (Attack of the Lederhosenzombies)
Rastislav (Socialistický Zombi Mord)

just to mention some, and of course

Sam (The Evil Dead)

as well as

Peter (Braindead)

see https://de.wikipedia.org/wiki/Zombiefilm

**Comment by nmueller18** [comment]
What about something more classical? At the moment, I read Harris Cicero-book "Titan", so "O tempore, o mores" springs to my mind.

**Comment by MartinHinz** [comment]
Which is a nice idea, but we have to think about the future. What for v 1.1, 1.2, 1.3, 2.0, 2.1...? :-)

**Comment by nmueller18** [comment]
Cui bono?
Veni, vidi, vici ...
Alea iacta est ...
Ceterum censeo Carthaginem esse delendam ...

**Comment by nevrome** [comment]
As a side note: I'm really glad, that we're finally talking about the **important** issues.

**Comment by MartinHinz** [comment]
He, come on, it is important for you fame in the posterity! What is the name with which you want to become famous? Cui bono, Dummkopf or Kiss my Ass?

Side note: I think one aspect why this group works is that we have an identity token due to its name. Do not ignore the power of a true name. Remember YHWH.

**Comment by nmueller18** [comment]
I also very much liked Christoph's idea of famous archaeologists (preferable female) or important cemeteries.

**Comment by MartinHinz** [comment]
+1 for the cemeteries

nothing against archaeologists, especially not female, but the cemeteries are much more related.

So mortAAR 1.0 Odagsen?

**Comment by nmueller18** [comment]
+1 from me for mortAAR 1.0 Odagsen

**Comment by FFaupel** [comment]
+ 1 for mortAAR 1.0 Odagasen
But next time perhaps somethink not related to the neolithic?! Everything in Kiel seems to be about neolithic stuff...

**Comment by nmueller18** [comment]
Good point. I suggest "Jastorf" for mortAAR 2.0.

**Comment by MartinHinz** [comment]
Suggestion was a tribute to Christoph, fine with something Iron Age for 2.0 (maybe a tribute to Nils, eg. 'Schirndorf').

**Comment by quassinja** [comment]
Decided to Odagsen, closed.
