### ISSUE TITLE
PreRelease ToDo: Fix group name in tabular output

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#25]
I know it is distressful but at least on my system the problem with the group-name not included in the tabular output of the life table function still persists (e.g., ":female" instead of "sex:female"). Is this just me (or more specifically, my Mac)?

**Comment by nevrome** [comment]
7c8f034341da8f125bfdbd329577b25d8b44fe6b. Does this fix it for you? Passing the attribute on correctly is a royal pain in the ass.

**Comment by nmueller18** [comment]
Yes, this fixed it!
