### ISSUE TITLE
PostRelease: Quickcheck tests

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/mortAAR#26]
[This](https://github.com/peterhurford/checkr) package will be on CRAN [soon](https://github.com/peterhurford/checkr/issues/34#issuecomment-335547473). We should use this for a much more reliable test infrastructure.

**Comment by MartinHinz** [comment]
That package seems to be not very active. Would suggest further rely on testthat.

**Comment by nevrome** [comment]
There's also [this](https://github.com/RevolutionAnalytics/quickcheck) one. Also not very active. :-1: 
 This is not meant to replace testthat but to increase the range of test cases. I still think this is very important.
