### ISSUE TITLE
Prerelease: winbuilder error message

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#27]
During the winbuilder check (https://win-builder.r-project.org/D7z18KlyQafp/) in "install.out" the following error message is generated:

`During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'mixtrak.R.dev'
2: package 'mixtrak.R.dev' in options("defaultPackages") was not found `

Where does 'mixtrak.R.dev' stems from? Any ideas?

All other checks (local mac, travis linux, winbuilder) are passed. This is the only one remaining before release!

**Comment by nevrome** [comment]
We're not using mixtrak.R.de. I seems to be a package to automatically [prepare an R development environment](https://github.com/mixtrak/mixtrak.R.dev). Maybe Uwe Ligges is using this to prepare the build setup and something is not correctly configured? 

What do you think about this, @benmarwick? You've probably seen more winbuilder builds than I have.

**Comment by nevrome** [comment]
I thought about this error now for an hour. It's one of the weirdest things I've ever encountered.

@mixtrak Do you have an idea what's going on here? Did you use the winbuilder lately managed to somehow influence our build with your [.onLoad function](https://github.com/mixtrak/mixtrak.R.dev/blob/342d1f3bd3919fc4ff768fc582007918d35bcfee/R/zzz.R#L90-L95)? Until now I was sure that that's not even possible.

**Comment by nevrome** [comment]
@ctietze91 and @chrinne could you please run a check on your windows computers? Does this error also appear locally?

**Comment by nevrome** [comment]
I just sent an other package ([rdoxygen](https://github.com/nevrome/rdoxygen)) to the winbuilder and got the same error. 

```
During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'mixtrak.R.dev'
2: package 'mixtrak.R.dev' in options("defaultPackages") was not found 
* installing *source* package 'rdoxygen' ...
** libs
``` 

I'm pretty confident now that the error is not caused by mortAAR.

**Comment by nmueller18** [comment]
That is a relief! But how do we proceed from now? Will you confront Uwe Ligges with the results?

**Comment by nevrome** [comment]
Let's just wait for @mixtrak's input. Maybe I'm completely wrong - maybe it will all sort itself out.

**Comment by benmarwick** [comment]
I've never seen that before, it does look like some kind of contamination from another process. I cloned mortAAR and did some win build tests:

- I ran `rhub::check_on_windows()` and got a little warning with the references in the vignette (maybe some exotic character that this version of pandoc-citeproc can't handle?) https://builder.r-hub.io/status/mortAAR_1.0.0.tar.gz-5c01ecd09a51406bbddd83e17387c3cf. But nothing in the [00install.out](https://artifacts.r-hub.io/mortAAR_1.0.0.tar.gz-5c01ecd09a51406bbddd83e17387c3cf/mortAAR.Rcheck/00install.out
) there.

- I also tried `devtools::build_win()` and got a few LaTeX errors (in [00check.log](https://win-builder.r-project.org/wrvJcnbw49zf/00check.log)) and the same mixtrak.R.dev error in [00install.out](https://win-builder.r-project.org/wrvJcnbw49zf/00install.out) that you report above. 

So I think we might need to bring this to the attention of Uwe.Ligges@r-project.org, this is a problem with CRAN's winbuilder.

**Comment by ghost** [comment]
Oh dear, this is definitely my fault. I'm kind of new to package building and I submitted my package (which extensively modifies the environment) to winbuild. The culprit is certainly in the .onLoad hook function of my package.

The most persistent effect of the .onLoad hook is that mixtrak.R.dev automatically modifies the .Rprofile to include code which adds itself to R's defaultPackages. This means mixtrak.R.dev is auto-loaded along with other R core packages in every R session.

The solution (hopefully) would be to delete the offending code from the .Rprofile (or delete .Rprofile entirely) and refrain from ever loading {mixtrak.R.dev} again (because it would just re-add the code to .Rprofile). Once {mixtrak.R.dev} is removed from R's list of auto-load packages, I don't think any of the other environment changes should be persistent because they're all set in the .onLoad hook function. It's probably worth checking the rest of the function code, however.

The offending code from the .onLoad function, which is injected into the .Rprofile, is included below.

```
  # Auto-load {mixtrak.R.dev} -----------------------------------------------
  
  # Auto-load package options are not preserved between sessions; need to inject
  # code into the .Rprofile.
  
  # The quoted code in this object, when evaluated, will add {mixtrak.R.dev} to
  # the auto-load package list:
  autoload_mixtrak <- quote(
    if(!"mixtrak.R.dev" %in% getOption("defaultPackages")) {
      options(defaultPackages = c(getOption("defaultPackages"),
                                  "mixtrak.R.dev"))
    }
  )
  
  # Find .Rprofile directory (= user's HOME directory)
  home_dir <- Sys.getenv("HOME")
  rprofile_path <- paste(home_dir, ".Rprofile", sep = "/")
  # If .Rprofile is absent, create with appropriate code
  if (!file.exists(rprofile_path)) {
    packageStartupMessage("Creating .Rprofile in home directory and adding {mixtrak.R.dev} to R startup packages")
    cat("", # Leading newline in case file does not contain trailing newline
        "# Auto-load package mixtrak.R.dev on R startup",
        deparse(autoload_mixtrak),
        sep = "\n",
        file = rprofile_path,
        append = TRUE)
  }
  
  # Check whether existing .Rprofile file is missing the code. Note that this
  # looks for an _exact_ match to the code contained in `autoload_mixtrak`. If
  # .Rprofile is missing this _exact_ string, it will be appended - even if
  # auto-loading of {mixtrak.R.dev} is implemented in some other way.
  if(!grepl(
    pattern = paste(deparse(autoload_mixtrak), collapse = ""),
    x = paste(readLines(con = rprofile_path), collapse = ""),
    fixed = TRUE
    )) {
    # Append relevant code to existing file:
    packageStartupMessage("Appending .Rprofile to persistently auto-load {mixtrak.R.dev} on R startup")
    cat("", # Leading newline in case file does not contain trailing newline
        "# Auto-load package mixtrak.R.dev on R startup",
        deparse(autoload_mixtrak),
        sep = "\n",
        file = rprofile_path,
        append = TRUE)
  }
  # Note further that this will fail with an error if a .Rprofile does not 
  # exist/is not found in that location; this should be impossible because of
  # the preceding if-statement but you never know. One of these days I'll learn
  # `tryCatch()` and fix it; then I can combine the if conditions anyway.
```

Apologies for unintentionally messing with the build server - I guess if I thought about it at all I thought build tests were done in a sandbox of some kind.

**Comment by ghost** [comment]
I suppose I should be sending this information and confession to Uwe instead, yes?

**Comment by nmueller18** [comment]
> I suppose I should be sending this information and confession to Uwe instead, yes?

That would be nice. Thanks for clarifying the issue!

**Comment by ghost** [comment]
Update: Uwe emailed me to say he's fixed the issue and advised me never to write to the user's filespace without prompting the user to agree and explicitly specify a path/filename. Consider me suitably (if gently) chastened.

Hopefully your build checks shouldn't throw any more warnings.
