### ISSUE TITLE
PostRelease: as.mortaar_life_table and as.mortaar_life_table_list

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/mortAAR#29]
I think we forgot the as. functions....

**Comment by nevrome** [comment]
What defines a mortaar_life_table? Which variables have to be present? The as.-functions could also be used to transform objects from other demography packages.

Let's discuss this in the next ISAAK-meeting. I think we can make this a PostRelease issue.

**Comment by nevrome** [comment]
Other packages with life table implementations are [LifeTables](https://cran.r-project.org/web/packages/LifeTables/index.html) and [demography](https://github.com/robjhyndman/demography).

**Comment by nmueller18** [comment]
@nevrome: Can't this be closed? The as-functions do exist now.

**Comment by nevrome** [comment]
Yes - can be closed. 

What I would do differently now is that I would make `mortaar_life_table` inherit explicitly from tibble. That has some advantages -- e.g. a better integration with the tidyverse tools. Here's the relevant code from c14bazAAR:

https://github.com/ropensci/c14bazAAR/blob/568cb4b962f74289b74905dc13233d052576a758/R/c14_date_list_basic.R#L33-L61

**Comment by nmueller18** [comment]
I suppose this is mainly something "under the hood"? If it does not break any code (which you oversee better than me), please go ahead!
