### ISSUE TITLE
function1() could be replaced by a call to tidyr::separate()

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/mortAAR#3]
I think `tidyr::separate()` does the same thing as `mortAAR::function1()` -- and it's a lot more flexible and foolproof. 

```
test <- read.table("data-raw/siedl.txt",header=T,sep="\t")

library(mortAAR)
function1(test, "Jahrefeld")

library(tidyr)
tidyr::separate(test, Jahrefeld, into = c("from", "to"), remove = FALSE)
```

I think we could mention this usecase in a vignette or an example, but we don't need to cover it with an own function in mortAAR.

**Comment by whamer** [comment]
I agree to that. I just created function1 since I didn´t know the separate function of the tidyr package ...

**Comment by nevrome** [comment]
Ok - I guess we can remove `function1` but keep its functionality in mind.
