### ISSUE TITLE
PostRelease: Uncomment summary-function

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#30]
Comment from CRAN:

For your next version:
Please uncomment the example in summe.Rd:
#summentest=summe(c(1,2,NA,4),c(5,6,7,8)

**Comment by MartinHinz** [comment]
Would also suggest renaming 'summe' to something more speaking!?

**Comment by nmueller18** [comment]
Somehow I have broken travis with my last commit. I probably committed and merged in the wrong order ... :-(

I am now very reluctant to merge the last pull request, especially as there is some conflict in the Namespace. That said, is it really useful to export the summe-replacement?
