### ISSUE TITLE
Improvements in subsetting for plotting

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#41]
At the moment, it is cumbersome to subset data for plotting (i. e., only a selection of the grouping variable). This is important because sometimes the plot is too crowded because of too many categories.

**Comment by nevrome** [comment]
Would you mind explaining this with some example code? I don't see how this is cumbersome:
```
plot(odagsen[["margo orbitalis"]])
```

**Comment by nmueller18** [comment]
I have problems with plotting more than one category.

`plot(muensingen[["female"]])` does work as does `plot(muensingen$female)`.

However, `plot(muensingen$female,muensingen$male)` or `plot(muensingen[["female","male"]])` throws an error. I would be happy about an easy solution!

**Comment by nevrome** [comment]
A `mortaar_life_table_list` is nothing more than a glorified `list`. Multiple list elements in R can be accessed like this:
```
odagsen[c("margo orbitalis", "corpus mandibulae")]
``` 
The result of this operation is only a `list`, not a `mortaar_life_table_list`. So it has to be converted back:
```
as.mortaar_life_table_list(odagsen[c("margo orbitalis", "corpus mandibulae")])
```
I think it would be possible to create a custom indexing operation `[]` for the `mortaar_life_table_list` class to avoid this step. @MartinHinz?

Another solution for your initial problem could be to loop through all the groups:
```
sapply(odagsen, plot)
```

**Comment by nmueller18** [comment]
I am glad that apparently I have not overlooked an obvious solution.

> So it has to be converted back: as.mortaar_life_table_list(odagsen[c("margo orbitalis", "corpus mandibulae")])

This I would call "cumbersome" ...

> I think it would be possible to create a custom indexing operation [] for the mortaar_life_table_list class to avoid this step. @MartinHinz?

This sounds like a possible solution.

> Another solution for your initial problem could be to loop through all the groups: sapply(odagsen, plot)

I would rather prefer to see the plots for the categories together.

**Comment by nevrome** [comment]
OK. I guess it's technically correct that `mortaar_life_table_list` is something like a vector class. Hadley [says](http://adv-r.had.co.nz/S3.html) we should implement accessor functions in this case:

> When implementing a vector class, you should implement these methods: length, [, [<-, [[, [[<-, c. (If [ is implemented rev, head, and tail should all work).

I experimented with this. Here's a first prototype:

```
`[.mortaar_life_table_list` <- function(x, i) {
  class(x) <- "list"
  mortAAR::as.mortaar_life_table_list(x[i])
}
```

If you load this function you can do something along the lines of

```
odagsen[c("corpus mandibulae", "margo orbitalis")]
```
without losing the class information.

I thought that we don't have to do this, because the `mortaar_life_table_list` inherits from `list` and therefore has all this abilities. But you're right: It's more convenient/generally better to have it directly for this class. I hope this doesn't cause any harm down the line. We can talk about the implementation tomorrow in the ISAAK meeting.

**Comment by nmueller18** [comment]
Your prototype works at least for me! (you just always have to mind the actual kind of parenthesis ["[" or "("])

**Comment by nevrome** [comment]
> “If list x is a train carrying objects, then x[[5]] is the object in car 5; x[4:6] is a train of cars 4-6.”

— @RLangTip (found [here](http://adv-r.had.co.nz/Subsetting.html#subsetting-operators))

**Comment by nevrome** [comment]
I tried to find out how exactly we should do this and already got a very good answer: https://stackoverflow.com/questions/53207515/how-to-implement-extracting-subsetting-functions-for-custom-s

Excellent! We can do this now!

**Comment by nevrome** [comment]
```
`[.mortaar_life_table_list` <- function(x, i) {
  as.mortaar_life_table_list(NextMethod())
}

`[<-.mortaar_life_table_list` <- function(x, i) {
  stopifnot(is.mortaar_life_table_list(value))
  NextMethod()
}

`[[<-.mortaar_life_table_list` <- function(x, i, value) {
  stopifnot(is.mortaar_life_table(value))
  NextMethod()
}

`$<-.mortaar_life_table_list` <- function(x, i, value) {
  stopifnot(is.mortaar_life_table(value))
  NextMethod()
}
```

**Comment by nmueller18** [comment]
Something like 

`plot(muen_result[c(1,3)])`

or

`plot(muen_result[c("male","female")]`

works very nicely and as expected now. If you want to combine life tables from different data set, then you have to define separate lists which then have to be renamed, but this is permissible to expect from the user. Issue resolved!
