### ISSUE TITLE
Plot option "color" does not work

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#47]
For the new branch "Plot_option_line_kind" I have tried to implement an option to print the lines in the plots in color. Simply replacing line 115 in master

`  my_plot <- ggplot2::ggplot(my_x, ggplot2::aes_string(x="a",y=variable_name,lty="dataset"))`

with

`  my_plot <- ggplot2::ggplot(my_x, ggplot2::aes_string(x="a",y=variable_name,color="dataset"))`

does work as expected, it only throws an error: `Fehler: measure variables not found in data: color`.
The way I tried to parametrize it in the new branch does not work, however.

**Comment by nmueller18** [comment]
Obviously, I did not test it thoroughly enough. After restarting everything, it seems to work as expected.

**Comment by MartinHinz** [comment]
Seems to work as aspected on my instance, too. So closing the issue?

**Comment by nmueller18** [comment]
Gladly! And merging the branch, too?

**Comment by MartinHinz** [comment]
One Remark: 'line_kind' seems to me to be not the perfect choice for the parameter. But I do not have a better alternative: 'differentiation' would be the most meaningfull, but it is rather clumsy and also not very specific. So I can live with that, meaning: OK for merge.
