### ISSUE TITLE
Proliferation of functions in the documentation

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#48]
The help file starts  to get inflated. It seems that the "rdname"-tag is ignored so that functions appear in the index list which are supposed to be subsumed under other entries. Any easy solutions?

**Comment by nevrome** [comment]
Can you give an example where the documentation is broken?

**Comment by nmueller18** [comment]
This is how the index of mortAAR looks on my system:

![mortAAR_index](https://user-images.githubusercontent.com/20249289/62656336-3f37cb00-b964-11e9-89c8-d3dfb33c4b54.png)

**Comment by nevrome** [comment]
I don't think this is an important issue. But it seems as if you could write your own INDEX file if you really want: https://stackoverflow.com/questions/35671332/add-sections-to-r-packages-help-documentation

**Comment by nmueller18** [comment]
It certainly does not impact the core functionality but I am irritated and would like to know why the `rdname`-tag, which is supposed to prevent this proliferation, does not do what it should do.

**Comment by nmueller18** [comment]
I have accomplished to reduce the number of functions in the index with the `@noRd`- and the `@keywords internal`-tag.

**Comment by nevrome** [comment]
Not sure if this is good. Do the functions still work as before?

**Comment by nmueller18** [comment]
At least the checks and testthat-tests threw no error. Would this be the case if the functions do not work? `@noRd` suppresses the creation of a documentation file for a respective function, `@keywords internal`creates the documentation file, but does not add it to the index file. It still can be accessed via `?function`.

**Comment by nevrome** [comment]
Interesting! I did not know that you could use this combination to "hide" class methods.

**Comment by nmueller18** [comment]
Unfortunately, it works only partially. `as.mortaar_life_table`, `as.mortaar_life_table_list` and `mortaar_life_table` are aliases of each other. You can hide either all or none, but you do not have the option to hide only two of the three (one would be enough, IMHO).
