### ISSUE TITLE
Last checks of mortAAR 1.1 Schirndorf before release

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#57]
mortAAR seems to be ready to be put back on CRAN where it has been removed due to some instable dependencies. The new version is 1.1 and includes many new functions.
It would be great if some of you would bother to test and have a look on the new vignettes ("Life table corrections" and "Reproduction"). @nevrome suggested to put the vignettes together via bookdown which seems to be a reasonable idea – for the next release.

**Comment by dakni** [comment]
impressive work! tested the latest vignette and everything works.

**Comment by capsizingHR** [comment]
Hey, I tried the vignettes also and didn't see any problems except that some names of authors are not correctly displayed in the references. I gave it a very quick look but couldn't see any reason for this neither in the vignettes nor the bib-file.

**Comment by nevrome** [comment]
Looks fine to me. Excellent work, @nmueller18!

**Comment by nevrome** [comment]
@capsizingHR 

I don't see any issue with the author names on my system. Am i missing something or could this be a reason of your local setup? I guess rendering these references is done by pandoc-citeproc and pandoc is shipped with RStudio afaik.

![image](https://user-images.githubusercontent.com/10789038/100627285-1db3dd00-3327-11eb-8c59-eddd3cb448eb.png)

**Comment by capsizingHR** [comment]
Well, I'm rendering it in RStudio and the strange thing is, that there is not a problem with every author name but just some. And can't see any difference to the other entrys in the bib but it's always the same names that are affected. 

![grafik](https://user-images.githubusercontent.com/44018301/100640694-04b32800-3337-11eb-8d3a-302838ac6eba.png)

**Comment by nevrome** [comment]
What is the problem in this screenshot?

**Comment by nmueller18** [comment]
I can also see no problems. Anyway, hopefully, such problems can be solved by moving all vignettes to bookdown for the next release.
Many thanks to all of you for your feedback (online and offline)!!
