### ISSUE TITLE
lapply(life_table, lt.function) falls back on default values

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#59]
Unfortunately, the strategy to cater at the same time for mortaar_life_tables as well as mortaar_life_table_lists does not seem to work properly. In the case of mortaar_life_table_lists, the code snippet `lapply(x, lt.function)` falls back on default values, any custom values are ignored. Therefore, the task is to pipe custom values through the function `lt.function.mortaar_life_table_list`.

**Comment by nevrome** [comment]
Additional arguments can just be added after the `FUN` argument of `lapply`. e.g.

```
lapply(list(c(1,2,3), c(4,5,6)), tail, n = 2)
```

**Comment by nmueller18** [comment]
But how are these arguments passed to the sub-function responsible for dealing with the mortaar_life_table_lists? Take this example from the documentation for the reproduction indices:

```
odagsen <- life.table(list(
 "corpus mandibulae" = odagsen_cm[c("a", "Dx")],
   "margo orbitalis" = odagsen_mo[c("a", "Dx")]
 ))
 lt.reproduction(odagsen)
```
The result is identical to all of the following examples which should not be the case:
```
lt.reprodcution(odagsen, fertility_rate = "BA_power")
lt.reproduction(odagsen, fertility_rate = "BA_power",gen_len = 30)
lt.reproduction(odagsen, fertility_rate = "BA_power",gen_len = 30,growth_rate = 2)
```
What obviously happens is that this code
```
lt.reproduction.mortaar_life_table_list <- function(life_table, fertility_rate = "BA_log", growth_rate = "fertility",  gen_len = 20) {
  lapply(life_table, lt.reproduction)
}
```
in all cases just uses the default values. If no default values are given, the function fails.

**Comment by nevrome** [comment]
Right - that was a mistake. But couldn't you just fix it with the syntax I provided above? E.g.

```
lt.reproduction.mortaar_life_table_list <- function(life_table, fertility_rate = "BA_log", growth_rate = "fertility",  gen_len = 20) {
  lapply(life_table, lt.reproduction, fertility_rate = fertility_rate, growth_rate = growth_rate, gen_len = gen_len)
}
```

Does this work?

**Comment by nmueller18** [comment]
Of course, you are right. I had tried it with
```
lapply(life_table, lt.reproduction, fertility_rate, growth_rate, gen_len)
```
but your solution works as suggested. Many thanks! I will now update all functions that follow the same logic accordingly.
