### ISSUE TITLE
Bug - representativity table

### ISSUE THREAD

**Issue by hrncirv** [ISAAKiel/mortAAR#62]
Hi, I probably found a bug in `lt.representativity.mortaar_life_table` (**representativity.R** file).

Line 74: There should be `mortality$q15_5` instead of `mortality$q10_5`.
Line 77:  There should be `mortality$q0_5 / mortality$q15_5` instead of `mortality$q0_5 / mortality$q10_5`

**Comment by nmueller18** [comment]
Thank you! Indeed, the numbers are wrong. However, funnily, the test still returns the true answer. I will correct this as soon as possible.

**Comment by nmueller18** [comment]
Fixed in upcoming vers. 1.1.3
