### ISSUE TITLE
PostRelease ToDo: Fancy Code

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/mortAAR#8]
in general but in particular for the input (e.g. prep.life.table) function

aim: clean code, i.e. as little loops as possible; since dplyr and tidyverse things are already dependencies of the package their data-crunching tools could/should be used [R-Code 2.0 ...]

**Comment by nevrome** [comment]
Here's a nice example: Hadley's tidying a dataset that's pretty comparable to possible mortAAR input data.

https://vimeo.com/140687685#t=10m54s

**Comment by nmueller18** [comment]
@dakni , @nevrome: Is this still open?

**Comment by dakni** [comment]
i'd see it is extinct. ;)

Could/Should be closed

**Comment by nmueller18** [comment]
Thank you!
